# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b5579bb4fc5ce8181e85f55b5b0764ecdde6fedd03ca4e23416f03f77bb6a2c1bdf99f9f104b9b0f8286b61affe897c590cb9f14b646817c5fe30a68f8c3b17

test:
  secret_key_base: 863f8d0506f33f6e8700c5fd2eb06968b0198a349d9cbf4ed89d813f6504b3a5b9a37ef9f152011367943c6065dcfc8562d8bef15393a6b8256607e350daaac8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
